---
  - hosts: ubuntu_servers
    become: true

    tasks:
      - name: Include variables
        include_vars: variables.yml

      - name: Install aptitude
        apt:
          name: aptitude
          state: latest
          update_cache: true

      - name: Upgrade apt packages
        apt:
          upgrade: yes
  
      - name: Install required packages
        apt:
          name:
            - ufw
            - unattended-upgrades
            - update-notifier-common
            - git
            - vim
            - htop
            - tmux
            - ca-certificates
            - curl
            - fail2ban
          state: present

      - name: Setup user
        include_tasks: tasks/setup-user.yml

      - name: Install Docker
        include_tasks: tasks/docker.yml
  
      - name: Configure unattended upgrades
        include_tasks: tasks/unattended-upgrades.yml

      - name: Configure ssh
        include_tasks: tasks/ssh.yml

      - name: Configure fail2ban
        include_tasks: tasks/fail2ban.yml

      - name: Configure ufw
        include_tasks: tasks/ufw.yml
  
      - name: Autoremove packages
        apt:
          autoremove: yes
  
      - name: Clean apt cache
        apt:
          autoclean: yes
