---
- name: Create Podman systemd directory
  file:
    path: /etc/containers/systemd
    state: directory
    mode: '0755'

- name: Create nginx network quadlet
  copy:
    dest: /etc/containers/systemd/nginx.network
    content: |
      [Network]
      NetworkName=nginx
    mode: '0644'

- name: Create portainer container quadlet
  copy:
    dest: /etc/containers/systemd/portainer.container
    content: |
      [Unit]
      Description=Portainer Admin UI
      After=network-online.target

      [Container]
      Image=docker.io/portainer/portainer-ce:latest
      ContainerName=portainer
      # Expose Portainer UI (9443 for HTTPS)
      PublishPort=9000:9000
      #PublishPort=9443:9443
      #PublishPort=8000:8000
      # Persist data
      Volume=/home/{{ created_username }}/docker/portainer/data:/data
      # Mount the Podman socket so Portainer can manage the local engine
      Volume=/run/podman/podman.sock:/var/run/docker.sock
      # Portainer often requires privileged mode to manage the host engine
      #Privileged=true

      PodmanArgs=--privileged
      Network=nginx.network

      [Service]
      # Restart the container if it crashes
      Restart=always

      [Install]
      # Start at boot
      WantedBy=multi-user.target default.target
    mode: '0644'

- name: Create Portainer data directory
  file:
    path: /home/{{ created_username }}/docker/portainer/data
    state: directory
    owner: "{{ created_username }}"
    group: "{{ created_username }}"
    mode: '0755'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Portainer service
  systemd:
    name: portainer.service
    enabled: yes
    state: started
