- name: Setup user
  user:
    name: "{{ created_username }}"
    state: present
    shell: /bin/bash
    append: yes
    groups: sudo
    create_home: true

- name: Setup passwordless sudo for user
  copy:
    content: |
      {{ created_username }} ALL=(ALL) NOPASSWD: ALL
    dest: "/etc/sudoers.d/{{ created_username }}_nopasswd"
