---
- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Ensure systemd-timesyncd is enabled and started
  systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
    
- name: Check time synchronization status
  command: timedatectl status
  register: timedatectl_status
  changed_when: false

- name: Display time sync status
  debug:
    var: timedatectl_status.stdout_lines
