- name: Enable unattended upgrades for Debian and Ubuntu
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades
  when: ansible_facts["os_family"] == "Debian"

- name: Configure unattended upgrades for Ubuntu
  copy:
    content: |
      Unattended-Upgrade::Origins-Pattern {
          "origin=Ubuntu,codename=${distro_codename},label=Ubuntu";
          "origin=Ubuntu,codename=${distro_codename},label=Ubuntu-Security";
      };
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Security-Updates "1";
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-Time "04:00";
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
  when: ansible_facts["distribution"] == "Ubuntu"

- name: Configure unattended upgrades for Debian
  copy:
    content: |
      Unattended-Upgrade::Origins-Pattern {
          "origin=Debian,codename=${distro_codename},label=Debian";
          "origin=Debian,codename=${distro_codename},label=Debian-Security";
      };
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Security-Updates "1";
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-Time "04:00";
    dest: /etc/apt/apt.conf.d/52unattended-upgrades-local
  when: ansible_facts["distribution"] == "Debian"

- name: Enable unattended upgrades
  dpkg_selections:
    name: unattended-upgrades
    selection: install